spring:
  application:
    name: blog-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&userSSL=false
    username: root
    password: "#123456*"

server:
  port: 9090

# mybatis配置
mybatis:
  type-aliases-package: com.akbar.pojo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# jwt配置
akbar:
  jwt:
    secret-key: akbar
    TTl: 7200000 #以毫秒计算
    token-name: token